*** empty log message ***

diff --git a/net-dialup/freeradius/files/radius.init b/net-dialup/freeradius/files/radius.init
--- a/net-dialup/freeradius/files/radius.init
+++ b/net-dialup/freeradius/files/radius.init
@@ -1,11 +1,18 @@
 #!/sbin/runscript
 
+opts="${opts} reload"
+
 depend() {
 	need net
 	use dns
 }
 
 checkconfig() {
+	if [ ! -d /var/run/radiusd ] && ! mkdir /var/run/radiusd; then
+		eeror "Failed to create /var/run/radiusd"
+		return 1
+	fi
+	
 	if [ ! -f /etc/raddb/radiusd.conf ] ; then
 		eerror "No /etc/raddb/radiusd.conf file exists!"
 		return 1
@@ -16,26 +23,41 @@ checkconfig() {
 		return 1
 	fi
 
-	if [ -z "`grep radiusd /etc/passwd`" ]; then
-		eerror "radiusd user missing!"
+	RADIUSD_USER=`grep '^ *user *=' /etc/raddb/radiusd.conf | cut -d ' ' -f 3`
+	RADIUSD_GROUP=`grep '^ *group *=' /etc/raddb/radiusd.conf | cut -d ' ' -f 3`
+	if [ -n "${RADIUSD_USER}" ] && ! getent passwd ${RADIUSD_USER} > /dev/null ; then
+		eerror "${RADIUSD_USER} user missing!"
+		return 1
+	fi
+	if [ -n "${RADIUSD_GROUP}" ] && ! getent group ${RADIUSD_GROUP} > /dev/null ; then
+		eerror "${RADIUSD_GROUP} group missing!"
 		return 1
 	fi
 
-	return 0
+	#radius.log is created before privileges drop; we need to set proper permissions on it
+	[ -f radius.log ] || touch radius.log || return 1
+
+	chown -R "${RADIUSD_USER:-root}:${RADIUSD_GROUP:-root}" . && \
+		chmod -R u+rwX,g+rX . || return 1
 }
 
 start() {
-	# Comment out the following line to get faster startups
+	cd /var/log/radius #set the location of log files, including startup.log created by check-radiusd-config
 	checkconfig || return 1
 
 	ebegin "Starting radiusd"
-	start-stop-daemon --start --quiet --exec /usr/sbin/radiusd -- ${RADIUSD_OPTS} >/dev/null
+	start-stop-daemon --start --quiet --exec /usr/sbin/radwatch -- /usr/sbin/radiusd ${RADIUSD_OPTS} >/dev/null
 	eend $?
 }
 
 stop () {
 	ebegin "Stopping radiusd"
-	start-stop-daemon --stop --quiet \
-		--pidfile=/var/run/radiusd/radiusd.pid --retry 20
+	start-stop-daemon --stop --quiet --pidfile=/var/run/radiusd/radwatch.pid
+	eend $?
+}
+
+reload () {
+	ebegin "Reloading radiusd"
+	start-stop-daemon --stop --signal HUP --quiet --pidfile=/var/run/radiusd/radiusd.pid
 	eend $?
 }
diff --git a/net-irc/eggdrop/files/eggdrop-installer b/net-irc/eggdrop/files/eggdrop-installer
--- a/net-irc/eggdrop/files/eggdrop-installer
+++ b/net-irc/eggdrop/files/eggdrop-installer
@@ -1,79 +1,84 @@
 #!/bin/bash
+# Copyright 1999-2005 Gentoo Foundation
+# Distributed under the terms of the GNU General Public License v2
+# $Header: /var/cvsroot/gentoo-x86/net-irc/eggdrop/files/eggdrop-installer,v 1.1.1.1 2005/11/30 09:48:59 chriswhite Exp $
 
 source /etc/init.d/functions.sh || {
-  echo "$0: Could not source /etc/init.d/functions.sh!"
-  exit 1
+	echo "${0}: Could not source /etc/init.d/functions.sh!"
+	exit 1
 }
 
 # Checks to see if user is trying to install eggdrop as root.
 root_check() {
-
-echo "Installing Eggdrop"
-if [ "$HOME" = "/root" ] || [ `whoami` == "root" ];
-then
-   einfo "You should not be installing eggdrop as root."
-   einfo ""
-   einfo "Installing eggdrop as root leaves your computer vulnerable"
-   einfo "to attack from other irc clients. Please use the eggdrop-installer"
-   einfo "script as the user who you wish to run eggdrop with"
-   exit 1
-else
-  install_eggdrop
-fi
-
+	if [ "${HOME}" = "/root" ] || [ "$(whoami)" = "root" ]
+	then
+		ewarn "You should not be installing eggdrop as root."
+		ewarn
+		ewarn "Installing eggdrop as root leaves your computer vulnerable"
+		ewarn "to attack from other irc clients. Please use the eggdrop-installer"
+		ewarn "script as the user who you wish to run eggdrop with"
+		exit 1
+	fi
 }
 
 # Usage information
 usage() {
-cat << "USAGE_END"
-Usage: eggbot-installer [bot-name]
+	cat <<USAGE_END
+Usage: eggdrop-installer <bot-name>
 Install eggdrop for a specific user, creating the directories and files
 needed for eggdrop to run securely and safely.
 USAGE_END
-
-exit 1
+	exit 1
 }
 
-install_eggdrop()
-{
-   if [ ! -d $HOME/.eggdrop ]
-   then
-       mkdir -p $HOME/.eggdrop
-   fi
-      einfo "Creating directories for your $bot_name ..."
-      mkdir -p $HOME/.eggdrop/$bot_name 
-      mkdir -p $HOME/.eggdrop/$bot_name/logs 
-      mkdir -p $HOME/.eggdrop/$bot_name/filesys 
-      mkdir -p $HOME/.eggdrop/$bot_name/filesys/incoming 
-      mkdir -p $HOME/.eggdrop/$bot_name/text 
-      mkdir -p $HOME/.eggdrop/$bot_name/scripts
+# Install eggdrop
+install_eggdrop() {
+	einfo "Installing Eggdrop"
+	einfo
 
-      einfo "Creating symlinks to required files for your bot to run ...."
-      ln -s /opt/eggdrop/help $HOME/.eggdrop/$bot_name/help
-      ln -s /opt/eggdrop/language $HOME/.eggdrop/$bot_name/language
-      ln -s /opt/eggdrop/modules $HOME/.eggdrop/$bot_name/modules
+	root_check
 
-      einfo "Copying motd and banner ... "
-      cp /opt/eggdrop/text/* $HOME/.eggdrop/$bot_name/text
+	if [ -d "${bot_dir}" ]
+	then
+		einfo "Already found a bot home directory for ${bot_name}"
+		exit 1
+	fi
 
-      # I changed this from a symlink to a direct copy because the user
-      # might not have write permissions to /opt/eggdrop/scripts
-      # as well as they might have their own custom scripts. - zul<chuck_short@rogers.com>
-      cp /opt/eggdrop/scripts/* $HOME/.eggdrop/$bot_name/scripts
+	einfo "Creating directories for your eggdrop..."
+	for dir in logs filesys/incoming text tmp scripts var
+	do
+		mkdir -p "${bot_dir}/${dir}"
+	done
 
-      einfo "Finished..."
-      
-      einfo "Please edit your $HOME/.eggdrop/$botname/eggdrop.conf "
-      einfo "If you need any help pleaese refer to the man page, or "
-      einfo "eggdrop website at http://www.egghelper.org"
-      
-      cp /opt/eggdrop/eggdrop.conf $HOME/.eggdrop/$bot_name/eggdrop.conf
+	einfo "Creating symlinks to required files for your bot to run..."
+	for file in help language modules eggdrop
+	do
+		ln -s "/opt/eggdrop/${file}" "${bot_dir}/${file}"
+	done
+
+	einfo "Copying motd, banner, scripts and config file..."
+	cp /opt/eggdrop/text/* "${bot_dir}/text"
+	cp /opt/eggdrop/scripts/* "${bot_dir}/scripts"
+	cp /opt/eggdrop/eggdrop.conf "${bot_dir}/eggdrop.conf"
+
+	einfo "Finished..."
+	einfo
+	einfo "Please edit your ${bot_dir}/eggdrop.conf!"
+	einfo
+	einfo "The bot needs to be run from the ${bot_dir} directory."
+	einfo "Run 'cd ${bot_dir} && ./eggdrop -m eggdrop.conf'"
+	einfo "to create the user file and then remove the -m command line option"
+	einfo "to start your eggdrop bot."
+	einfo
+	einfo "If you need any help pleaese refer to the man page, or"
+	einfo "eggdrop website at http://www.egghelper.org/"
 }
 
-if [ ! -n "$1" ]
+if [ -z "${1}" ]
 then
-  usage
-else 
-  bot_name="$1"
-  root_check
+	usage
+else
+	bot_name="${1}"
+	bot_dir="${HOME}/.eggdrop/${bot_name}"
+	install_eggdrop
 fi
