*** empty log message ***

diff --git a/sys-cluster/util-vserver/files/vprocunhide b/sys-cluster/util-vserver/files/vprocunhide
--- a/sys-cluster/util-vserver/files/vprocunhide
+++ b/sys-cluster/util-vserver/files/vprocunhide
@@ -1,53 +1,18 @@
 #!/sbin/runscript
-# Copyright 1999-2004 Gentoo Foundation
+# Copyright 1999-2005 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
-
-depend() {
-	need localmount
-}
+# $Header: /var/cvsroot/gentoo-x86/sys-cluster/util-vserver/files/vprocunhide,v 1.1.1.1 2005/11/30 10:01:50 chriswhite Exp $
 
 start() {
-
-	ebegin "Fixing /proc entries visibility..."
-	lockfile=/var/run/vprocunhide.lock
-
-        /usr/lib/util-vserver/vprocunhide
-
-        rc=$?
-        case "$rc" in
-	2)	rc=0;;
-	esac
-        test "$rc" -ne 0 || touch "$lockfile"
-	eend $rc "Failed"
-
+	: ${UTIL_VSERVER_VARS:=/usr/lib/util-vserver/util-vserver-vars}
+	if [[ ! -e ${UTIL_VSERVER_VARS} ]]; then
+		eerror "Cannot find util-vserver installation"
+		eerror "(the file '$UTIL_VSERVER_VARS' would be expected)"
+		exit 1
+	fi
+	. ${UTIL_VSERVER_VARS}
+	
+	ebegin "Unhiding /proc entries"
+	${_VPROCUNHIDE}
+	eend $?
 }
-
-stop()
-{
-    ebegin "Stopping vprocunhide"
-    lockfile=/var/run/vprocunhide.lock
-    rm -f "$lockfile"
-    eend $? "Failed"
-}
-
-
-restart()
-{
-    stop
-    start
-}
-
-status()
-{
-     lockfile=/var/run/vprocunhide.lock
-
-     test -f $lockfile && {
-        echo $"/proc entries were fixed"
-        exit 0
-     }
-     echo $"/proc entries are not fixed"
-     exit 1
-
-}
-
-
